# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jobcli < Formula
  desc "Fast, single-binary job aggregation CLI."
  homepage "https://github.com/jimezsa/jobcli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jimezsa/jobcli/releases/download/v0.1.1/jobcli_0.1.1_darwin_amd64.tar.gz"
      sha256 "57f63c01b53d65306dda0b19f886ef5f0b0245f9012b24a823554da9827aa391"

      def install
        bin.install "jobcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jimezsa/jobcli/releases/download/v0.1.1/jobcli_0.1.1_darwin_arm64.tar.gz"
      sha256 "8e8460f6aed90c29baf2cb4edb3dce8b999548550657417b6e024ab5b546254f"

      def install
        bin.install "jobcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimezsa/jobcli/releases/download/v0.1.1/jobcli_0.1.1_linux_amd64.tar.gz"
      sha256 "19947fcd5afa678362a5ef94380ea36af2e3363ee3dc23f68070797dce7f5908"
      def install
        bin.install "jobcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimezsa/jobcli/releases/download/v0.1.1/jobcli_0.1.1_linux_arm64.tar.gz"
      sha256 "5dbc169d4c500ad2ff7893bb8a2e33b54f9b8022781063167c92d2f8df00d638"
      def install
        bin.install "jobcli"
      end
    end
  end
end
