# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jobcli < Formula
  desc "Fast, single-binary job aggregation CLI."
  homepage "https://github.com/jimezsa/jobcli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jimezsa/jobcli/releases/download/v0.1.2/jobcli_0.1.2_darwin_amd64.tar.gz"
      sha256 "79cbae2f4987191336826078aede5099dd0f736f1e1e947aacab56dbe34bd763"

      def install
        bin.install "jobcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jimezsa/jobcli/releases/download/v0.1.2/jobcli_0.1.2_darwin_arm64.tar.gz"
      sha256 "ca6832ddd4f376d2250fbafcb78b535cddcded721097f2e93528b4c9d81615d5"

      def install
        bin.install "jobcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimezsa/jobcli/releases/download/v0.1.2/jobcli_0.1.2_linux_amd64.tar.gz"
      sha256 "f0926617bfb799e7afaeb2edd5f8b9ddc2dd4aaf30b140bb79d8f4c706b05536"
      def install
        bin.install "jobcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimezsa/jobcli/releases/download/v0.1.2/jobcli_0.1.2_linux_arm64.tar.gz"
      sha256 "5d0e4ad6e22ddb95a2b9fb0c8d9639218c1aa65b07de9b54dc3e96bad42d97a9"
      def install
        bin.install "jobcli"
      end
    end
  end
end
