# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jobcli < Formula
  desc "Fast, single-binary job aggregation CLI."
  homepage "https://github.com/jimezsa/jobcli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jimezsa/jobcli/releases/download/v0.1.0/jobcli_0.1.0_darwin_amd64.tar.gz"
      sha256 "876b8b9350052f1ccc10615ae340db515b2f3ef6a1e934587236731bc0655a92"

      def install
        bin.install "jobcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jimezsa/jobcli/releases/download/v0.1.0/jobcli_0.1.0_darwin_arm64.tar.gz"
      sha256 "c42d7a1a993a28623209a2cc1182f53e832dc017530d513e802de0d3596a2987"

      def install
        bin.install "jobcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimezsa/jobcli/releases/download/v0.1.0/jobcli_0.1.0_linux_amd64.tar.gz"
      sha256 "d0802371161d7000ff863c0899ff5e1e33705b4e04a968ba2eec9f3049b9da35"
      def install
        bin.install "jobcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimezsa/jobcli/releases/download/v0.1.0/jobcli_0.1.0_linux_arm64.tar.gz"
      sha256 "83dace6fbbd75b0d9ebf24f7cae9bc6f8d6605b4235b82554517f221d8470946"
      def install
        bin.install "jobcli"
      end
    end
  end
end
