# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Papercli < Formula
  desc "Scientific papers from your terminal."
  homepage "https://github.com/jimezsa/papercli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jimezsa/papercli/releases/download/v0.1.0/papercli_0.1.0_darwin_amd64.tar.gz"
      sha256 "341b428459f99f71d1f7b767180e6c6ef6bdd5c4961285f0552f01d48cc02c86"

      define_method(:install) do
        bin.install "papercli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jimezsa/papercli/releases/download/v0.1.0/papercli_0.1.0_darwin_arm64.tar.gz"
      sha256 "6748e0c23cf24462299a4dd83dfd912d2ba6dac9314f52ecac39776a7d7ff91a"

      define_method(:install) do
        bin.install "papercli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimezsa/papercli/releases/download/v0.1.0/papercli_0.1.0_linux_amd64.tar.gz"
      sha256 "e9267113acdac3bbeca9e5b5940ec48c2f3e7bdbf5c6f2503b8ba0937961d9f2"
      define_method(:install) do
        bin.install "papercli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimezsa/papercli/releases/download/v0.1.0/papercli_0.1.0_linux_arm64.tar.gz"
      sha256 "7aee6b28682d80e7a2a125260aae09f8d53582cdf725e0a74b0f5076f3667316"
      define_method(:install) do
        bin.install "papercli"
      end
    end
  end
end
