# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Papercli < Formula
  desc "Scientific papers from your terminal."
  homepage "https://github.com/jimezsa/papercli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jimezsa/papercli/releases/download/v0.1.2/papercli_0.1.2_darwin_amd64.tar.gz"
      sha256 "7462c93fb205f39ab59bfcfc81897bb283057b112404613e171be25a5121ec2a"

      define_method(:install) do
        bin.install "papercli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jimezsa/papercli/releases/download/v0.1.2/papercli_0.1.2_darwin_arm64.tar.gz"
      sha256 "bb9f52c162ebf99d6b4a89a38446284dec9b3fe29934c5c15a31da69b8f99c2f"

      define_method(:install) do
        bin.install "papercli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimezsa/papercli/releases/download/v0.1.2/papercli_0.1.2_linux_amd64.tar.gz"
      sha256 "e1cf3bdc41683aea9ef24ecd2e7f117ab59a6b5dfdc7186aba789ca588e22f8a"
      define_method(:install) do
        bin.install "papercli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jimezsa/papercli/releases/download/v0.1.2/papercli_0.1.2_linux_arm64.tar.gz"
      sha256 "7cea350689d308ef81ac9c35e01f72293e4bf713e1d6dfa3c0f1a5d32eda1c0b"
      define_method(:install) do
        bin.install "papercli"
      end
    end
  end
end
